version: "3.9"

services:
  payment-db:
    image: postgres:13
    container_name: payment-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: POSTGRES
      POSTGRES_DB: paymentdb
    volumes:
      - scammer-reactive-volume:/var/lib/postgresql/data
    networks:
      - scammer-network

  payment-service:
    container_name: payment-service
    image: payment-db-service
    build: ./
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - payment-db
    networks:
      - scammer-network

volumes:
  local_postgres_payment_db:

networks:
  scammer-network:
    name: scammer-network
    driver: bridge