version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - scammer-network

  payment-db:
    image: postgres:13
    container_name: payment-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: POSTGRES
      POSTGRES_DB: paymentdb
    volumes:
      - scammer-reactive-volume:/var/lib/postgresql/data
    networks:
      - scammer-network

  payment-service:
    container_name: payment-service
    image: payment-db-service:0.0.1-SNAPSHOT
    build: ./
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - payment-db
    networks:
      - scammer-network

volumes:
  scammer-reactive-volume:
    external: true

networks:
  scammer-network:
    name: scammer-network
    driver: bridge