server:
  port: 8081

spring:
  kafka:
    bootstrapAddress: localhost:9092
    topic:
      payments: payments
      suspicious-payments: suspicious-payments
      checked-payments: checked-payments
    consumer:
      groupId: analyzer-group-id
  application:
    name: analyzer-reactive

redis:
  hostName: localhost
  port: 6379

feign:
  hystrix:
    enabled: true

hostPort:
  paymentService: http://localhost:8082

tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0