server:
  port: 8081

spring:
  kafka:
    bootstrapAddress: localhost:9092
    topic:
      payments: payments
      backoffPayments: backoff-payments
      suspicious-payments: suspicious-payments
      checked-payments: checked-payments
      backoff-payments: backoff-payments
    consumer:
      groupId: analyzer-group-id
      groupIdBackoff: analyzer-backoff-group-id

redis:
  hostName: localhost
  port: 6379

hostPort:
  paymentService: http://localhost:8082

app:
  durationPollMillis: 500
  signForHandleBackoffPayment: 10000
  retryCount: 3
  retryIntervalSeconds: 3
  redisTimeout: 10
  lastPayment: /payment/last-payment
  savePayment: /payment/save

logging:
  level:
    ru.neoflex.scammertracking.analyzer: debug